seed: 42

wandb:
  project: wan-t2v-flow-matching
  mode: online
  name: wan2_1_t2v_fm_updated

dist_env:
  backend: nccl
  timeout_minutes: 30

model:
  pretrained_model_name_or_path: Wan-AI/Wan2.1-T2V-1.3B-Diffusers

data:
  dataloader:
    _target_: nemo_automodel.components.datasets.diffusion.build_wan21_dataloader
    meta_folder: /lustre/fsw/portfolios/coreai/users/linnanw/hdvilla_sample/pika/wan21_codes/1.3B_meta/
    batch_size: 1
    num_workers: 2
    device: cpu
    num_nodes: 1

batch:
  batch_size_per_node: 8

training:
  num_epochs: 20

optim:
  learning_rate: 5e-6
  optimizer:
    weight_decay: 0.01
    betas: [0.9, 0.999]

flow_matching:
  use_sigma_noise: true
  timestep_sampling: uniform
  logit_mean: 0.0
  logit_std: 1.0
  flow_shift: 3.0
  mix_uniform_ratio: 0.1

fsdp:
  cpu_offload: true
  tp_size: 1
  cp_size: 1
  pp_size: 1

logging:
  save_every: 50
  log_every: 2

checkpoint:
  enabled: true
  checkpoint_dir: /opt/Automodel/wan_t2v_flow_outputs_base_recipe_checkpoint_NEW_new/
  model_save_format: torch_save
  save_consolidated: false
  restore_from: null