# FLUX.1 Text-to-Image Pretraining Configuration
#
# This configuration file is compatible with TrainDiffusionRecipe class
# (dfm/src/automodel/recipes/train.py) using FlowMatchingPipeline with FluxAdapter
#
# Pretraining initializes model with random weights (no pretrained loading)
#
# Launch with:
#   torchrun --nproc-per-node=8 examples/automodel/pretrain/pretrain.py \
#     -c examples/automodel/pretrain/flux_t2i_flow.yaml

# Model configuration
model:
  pretrained_model_name_or_path: "black-forest-labs/FLUX.1-dev"  # Used for config only
  mode: "pretrain"  # "pretrain" initializes with random weights
  cache_dir: null
  attention_backend: null

# Optimizer configuration
optim:
  learning_rate: 1e-4

  optimizer:
    weight_decay: 0.01
    betas: [0.9, 0.999]

# FSDP (Fully Sharded Data Parallel) configuration
fsdp:
  enable_fsdp: true
  dp_size: null  # Auto-calculate based on world_size
  dp_replicate_size: 1
  tp_size: 1
  cp_size: 1
  pp_size: 1
  cpu_offload: false
  activation_checkpointing: true
  use_hf_tp_plan: false

# Flow matching configuration - Flux specific
flow_matching:
  adapter_type: "flux"
  adapter_kwargs:
    guidance_scale: 3.5
    use_guidance_embeds: true
  timestep_sampling: "logit_normal"
  logit_mean: 0.0
  logit_std: 1.0
  flow_shift: 3.0
  mix_uniform_ratio: 0.1
  sigma_min: 0.0
  sigma_max: 1.0
  num_train_timesteps: 1000
  i2v_prob: 0.0  # Flux is image-only
  use_loss_weighting: true
  log_interval: 100
  summary_log_interval: 10

# Training step scheduler configuration
step_scheduler:
  num_epochs: 5000  # Pretraining typically requires many more epochs
  local_batch_size: 1
  global_batch_size: 8
  ckpt_every_steps: 2000  # Save less frequently during pretraining
  log_every: 10

# Data configuration - using multiresolution dataloader for Flux
data:
  dataloader:
    _target_: dfm.src.automodel.datasets.multiresolutionDataloader.build_flux_multiresolution_dataloader
    cache_dir: /lustre/fsw/portfolios/coreai/users/pthombre/Automodel/CICDNEW/DFM/FluxData8Examples
    train_text_encoder: false
    num_workers: 2
    base_resolution: [512, 512]  # Match the 512p resolution preset used in preprocessing
    dynamic_batch_size: false
    shuffle: true
    drop_last: false

# Checkpoint configuration
checkpoint:
  enabled: true
  checkpoint_dir: /lustre/fsw/portfolios/coreai/users/pthombre/Automodel/CICDNEW/DFM/flux_pretrain_outputs_8_example/
  model_save_format: torch_save
  save_consolidated: false
  restore_from: null

# Logging
wandb:
  project: flux-pretraining
  mode: online
  name: flux_pretrain_run_8_example

# Distributed environment
dist_env:
  backend: "nccl"
  init_method: "env://"

# Random seed
seed: 42
